version: '3.8'

services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - world-db
      - user-db
    command: npm run dev-container
    environment:
      - WORLD_DATABASE_HOST=world-db
      - USER_DATABASE_HOST=user-db

  world-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: world
      MYSQL_USER: world_user
      MYSQL_PASSWORD: world_password
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  
  user-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: user
      MYSQL_USER: user_user
      MYSQL_PASSWORD: user_password
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306